Реализовала новые классы
Julia3202/java-shareit pull request #1
Opened 2023-10-06 13:36 UTC by Julia3202

2023-10-06 21:48 UTC, Frilock requested changes
Добрый вечер, комментарии в коде

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto create(@RequestHeader("X-Sharer-User-Id") long userId, @RequestBody ItemDto itemDto) {
Данный литерал X-Sharer-User-Id повторяется более двух раз, вынесете в константу класса

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        if (item.getName().isBlank() || item.getName() == null) {
Используйте StringUtils.isBlank

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        if (item.getDescription() == null || item.getDescription().isBlank()) {
аналогично

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
> +@Component
Аннотации над интерфейсами бесполезны, главное чтоб они были над реализацией

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +public class ItemRepositoryImp implements ItemRepository {
Impl наверно

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +        System.out.println(itemList);
А это зачем? Либо используйте логгер либо уберите

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +        removeItem(user, id);
А зачем удалять? Вы же обновляете просто, вытащите и поля поменяйте

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImp.java
> +        if (itemDto.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +                bookingDto.getStart() != null ? bookingDto.getStart() : null,
А зачем все поля проверять так? Какой смысл от такой проверки

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +                itemDto.getDescription() != null ? itemDto.getDescription() : null,
Не нужно проверять в таком формате все поля, делайте просто itemDto,getDescriprion, если там нул то и так нул проставится

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserValidator.java
> +        if (user.getName() == null || user.getName().isBlank()) {
StringUtils

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserValidator.java
> +        } else {
else лишний, пишите сразу return

2023-10-06 21:48 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dao/UserRepository.java
> +@Component
лишняя аннотация

2023-10-07 09:17 UTC, Frilock requested changes
Добрый день, еще пара комментариев

2023-10-07 09:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserValidator.java
> +        if (user.getName().isBlank()) {
StringUtils.isBlank(user.getName) - надо подключить библиотеку от apache common 3
https://mvnrepository.com/artifact/org.apache.commons/commons-lang3

2023-10-07 09:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> -        if (item.getName().isBlank() || item.getName() == null) {
Написал комментарий с библиотечкой

2023-10-07 09:17 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImpl.java
> +        Optional.ofNullable(itemDto.getDescription()).ifPresent(x -> item.setDescription(itemDto.getDescription()));
Можно проще:
        Optional.ofNullable(itemDto.getDescription()).ifPresent(item::setDescription);
IDEA желтым должна подсвечивать

2023-10-07 13:11 UTC, Julia3202 commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImpl.java
> +        Optional.ofNullable(itemDto.getDescription()).ifPresent(x -> item.setDescription(itemDto.getDescription()));
Но идея мне ничего не подсвечивала...

2023-10-08 06:46 UTC, Frilock requested changes
Доброе утро, уже все почти отлично, еще пара комментариев

2023-10-08 06:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String USER_ID = "X-Sharer-User-Id";
static final поля принято располагать выше других

2023-10-08 06:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepositoryImpl.java
> +            String description = items.getDescription().toLowerCase();
Чтобы не приводить к регистру используйте - StringUtils.containsIgnoreCase

2023-10-08 06:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +@Slf4j
Лишняя аннотация

2023-10-08 06:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        User userRepo = userRepository.create(user);
А что за userRepo?) какое то неочевидное название поля

2023-10-08 06:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +@Data
Зачем она тут?

2023-10-08 15:34 UTC, Frilock approved these changes
Принято

2023-10-16 09:35 UTC, merged