Add bookings
Julia3202/java-shareit pull request #2
Opened 2023-10-25 22:41 UTC by Julia3202

2023-10-26 16:09 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе.

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingDtoItem.getItemId() == null) {
Вынесите всю валидацию в отдельный приватный метод

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Вещь с ID-" + bookingDtoItem.getItemId() + "не найдена."));
Сольется строка исключения

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus() == Status.WAITING) {
Инвертируйте условие, тогда можно будет убрать лишнюю вложенность

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new ValidationException("Передан неверный статус.");
Можно еще указывать какой

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return BookingMapper.toBookingDto(saveBooking);
Можно в 1 строчку обьединить эти 2

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +
Лишний пропуск строки

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Запрос с ID- " + bookingId + " не найден."));
Сольется строка

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case ("all"):
Сделайте енам с данными статусами и используйте его

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                        .map(BookingMapper::toBookingDto)
Модно результат сохранять в переменную, а map(..).collect(..) делать 1 раз в конце метода. Уберется дублирующий код

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +@Repository
Лишняя аннотация

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +    @Query("select b " +
Постарайтесь делать запросы в названии метода, вы же spring-data используйтесь

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemDto.getName() == null || itemDto.getName().isEmpty()) {
Используйте StringUtils.isEmpty

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        }
Вынесите валидацию в отдельный метод

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>          return ItemMapper.toItemDto(itemRepo);
Можно заинлайнить в 1 строку

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : items) {
Какая то очень сложная логика... попробуйте упростить цикл, или хотя бы вынесите дублирующий код в приватный метод

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>  public class ItemServiceImpl implements ItemService {
Над частью методов отсуствует транзакция

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
> +    void deleteByOwner_IdAndId(long userId, long id);
Придерживайтесь одного формата написания методов, предлагаю использовать camelCase

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/RequestServiseImpl.java
> +public class RequestServiseImpl {
Это что за класс?)

2023-10-26 16:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +@RequiredArgsConstructor
Над частью методов отсуствует транзакция

2023-10-26 16:09 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS requests (
Пропускайте строку между Созданием таблиц, иначе все сливается

2023-10-27 13:18 UTC, Julia3202 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus() == Status.WAITING) {
перепробовала 3 варианта, ошибки нет только в этом условии

2023-10-27 13:29 UTC, Julia3202 commented on src/main/java/ru/practicum/shareit/request/RequestServiseImpl.java
> +public class RequestServiseImpl {
Это в 13 спринте создавала сразу,потом буду дорабатывать

2023-10-28 06:09 UTC, Frilock requested changes
Доброе утро. Часть комментариев не поправили (они были свернуты)

2023-10-28 06:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +@RequiredArgsConstructor
Лишняя аннотация

2023-10-28 06:09 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    public Boolean validStartBooking(BookingDtoItem bookingDtoItem) {
Вообще, можете методы можете сделать статичными и не создавать экземпляр класса (там где используете)

2023-10-28 20:47 UTC, Frilock requested changes
Добрый вечер, еще ряд комментариев

2023-10-28 20:47 UTC, Frilock commented on pom.xml
> +		<dependency>
Сьехало форматирование

2023-10-28 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        List<Booking> bookingList;
замените на switch - case, вам надо state преобразовать к енаму  через ValueOf, затем значение сравнивать в блоках switch-case, причем приводить к нижнему регистру не нужно

2023-10-28 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (state.toLowerCase().equals(DateStatus.ALL.getNameStatus())) {
Аналогично

2023-10-28 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
>              log.info("Поле с названием не заполнено.");
А почему в info ошибку пишите?

2023-10-29 11:12 UTC, Julia3202 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        List<Booking> bookingList;
исправила,но пришлось вернуться к тому что return в каждом case. иначе не видит листа.

2023-10-30 04:59 UTC, Frilock requested changes
Доброе утро, не исправили

2023-10-30 04:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +            log.warn("Поле с названием не заполнено.");
На мой взгляд лучше error, но можно и так думаю

2023-10-30 04:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                break;
break можно не ставить

2023-10-30 04:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case "ALL":
еще раз....к вам приходит строка state. Ее нужно преобразовать к енам (используйте ValueOf), затем внутрь switch вы ставите только это значение, без преобразований к регистру.
Внутри блоков case нужно использовать не литералы, а значения данного енама - case ALL: ....

2023-10-31 06:37 UTC, Frilock approved these changes
Принято

2023-10-31 06:37 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Пользователь с ID" + userId + " не найден."));
Зачем дефис убрали?) у вас строка сольется ...

2023-10-31 06:37 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserValidatorService.java
> +    public User checkUser(Long userId) {
ByExist =)

2023-10-31 13:11 UTC, merged